#!/usr/bin/env python3
"""
Zhihu Article Batch Downloader
Compatible with scrap-article-list.py output
"""

import json
import os
import sys
import time
import re
from typing import List, Dict, Any
from datetime import datetime
from curl_cffi import requests

# Assuming these local modules exist based on your snippet
try:
    from html2markdown import PageToMarkdown
    from download_contents import extract_config_from_curl, extract_metadata_from_html, sanitize_filename
except ImportError:
    print("[Error] Missing dependency modules (html2markdown.py or download_contents.py)")
    sys.exit(1)

class ArticleDownloadPipeline:
    def __init__(self, assets_file: str, output_dir: str = "./downloads/articles"):
        self.assets_file = assets_file
        self.output_dir = output_dir
        self.articles = []
        self.session = requests.Session()
        self.headers = {}
        self.md_converter = PageToMarkdown(skip_empty=True)
        
        self.stats = {
            'total': 0,
            'success': 0,
            'failed': 0,
            'failed_urls': []
        }
        
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def load_articles(self) -> bool:
        """Load articles from the JSON generated by scrap-article-list.py"""
        if not os.path.exists(self.assets_file):
            print(f"[Error] File not found: {self.assets_file}")
            return False
        
        try:
            with open(self.assets_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                # Handle both list format and wrapped format
                self.articles = data if isinstance(data, list) else data.get('data', [])
        except Exception as e:
            print(f"[Error] Failed to parse JSON: {e}")
            return False
        
        self.stats['total'] = len(self.articles)
        print(f"[Info] Found {len(self.articles)} articles in {self.assets_file}")
        return len(self.articles) > 0

    def load_headers(self, quick_mode: bool = False) -> bool:
        """Load headers from file or via cURL paste"""
        header_cache = "headers.json"
        
        if quick_mode and os.path.exists(header_cache):
            with open(header_cache, 'r', encoding='utf-8') as f:
                self.headers = json.load(f)
                print(f"[Success] Loaded cached headers from {header_cache}")
                return True

        print("\n--- Please paste cURL from any Zhihu Article Page ---")
        print("Tip: Press Ctrl+D (Unix) or Ctrl+Z+Enter (Win) to finish\n")
        
        curl_input = sys.stdin.read()
        if not curl_input.strip(): return False
        
        _, headers = extract_config_from_curl(curl_input)
        if not headers: return False
        
        # Clean up headers
        headers.pop('Accept-Encoding', None)
        self.headers = headers
        
        # Save for next time
        with open(header_cache, 'w', encoding='utf-8') as f:
            json.dump(headers, f, indent=2)
        print(f"[Success] Headers configured and cached.")
        return True

    def download_article(self, article: Dict[str, Any], index: int) -> bool:
        article_id = str(article.get('id'))
        # Use the title from the JSON as fallback
        raw_title = article.get('title', f'article_{article_id}')
        url = f"https://zhuanlan.zhihu.com/p/{article_id}"
        
        print(f"[{index + 1}/{self.stats['total']}] Downloading: {raw_title}")
        
        try:
            resp = self.session.get(
                url, 
                headers=self.headers, 
                impersonate="chrome110", 
                timeout=20
            )
            resp.raise_for_status()
            
            # Extract metadata from HTML, but prefer JSON data if HTML fails
            html_content = resp.text
            meta = extract_metadata_from_html(html_content)

            # Reconciliation between JSON data and HTML data
            title = sanitize_filename(article.get('title') or meta['title'])
            author = sanitize_filename(article.get('author') or meta['author'])
            # Format: YYYY-MM-DD from '2023-01-01 12:00:00'
            date_prefix = article.get('created_time', '0000-00-00').split(' ')[0]
            
            filename = f"{date_prefix}_{author}_{title}.md"[:200]
            filepath = os.path.join(self.output_dir, filename)
            
            md_body = self.md_converter.convert(html_content, url)
            
            frontmatter = (
                f"---\n"
                f"title: {article.get('title')}\n"
                f"author: {article.get('author')}\n"
                f"date: {article.get('created_time')}\n"
                f"source: {url}\n"
                f"stats: {article.get('stats')}\n"
                f"---\n\n"
            )
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(frontmatter + md_body)
                
            print(f"  [OK] Saved: {filename}")
            return True
            
        except Exception as e:
            print(f"  [Failed] {url} - Error: {e}")
            self.stats['failed_urls'].append({'id': article_id, 'error': str(e)})
            return False

    def run(self, delay: float = 2.0):
        if not self.load_articles() or not self.load_headers(quick_mode=True):
            return

        print(f"\nTarget: {self.stats['total']} articles. Output: {self.output_dir}")
        if input("Proceed? (y/n): ").lower() != 'y': return

        for i, article in enumerate(self.articles):
            if self.download_article(article, i):
                self.stats['success'] += 1
            else:
                self.stats['failed'] += 1
            time.sleep(delay)

        print(f"\nFinished! Success: {self.stats['success']}, Failed: {self.stats['failed']}")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('file', help='The JSON file from scrap-article-list.py')
    parser.add_argument('--out', '-o', default='./downloads/articles', help='Output directory')
    parser.add_argument('--delay', '-d', type=float, default=2.0, help='Seconds between requests')
    
    args = parser.parse_args()
    
    pipeline = ArticleDownloadPipeline(args.file, args.out)
    pipeline.run(delay=args.delay)

if __name__ == "__main__":
    main()